# Generated by Django 5.0.6 on 2024-06-13 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
    ]
